# Generated by Django 2.1.5 on 2019-02-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
