# Generated by Django 2.1.5 on 2019-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='link',
        ),
    ]
