# Generated by Django 2.1.5 on 2019-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_remove_trainer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter'),
        ),
    ]
