# Generated by Django 2.1.5 on 2019-02-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_auto_20190227_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
