# Generated by Django 2.1.5 on 2019-02-27 06:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_auto_20190227_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Content'),
        ),
    ]
