# Generated by Django 2.1.5 on 2019-02-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_auto_20190227_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='body',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='crossfit',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Crossfit'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gap',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='GAP'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='spinning',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Spinning'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='step',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Step'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='yoga',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Yoga'),
        ),
    ]
