# Generated by Django 2.1.5 on 2019-02-25 07:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subtitle',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Subtitle'),
        ),
    ]
