# Generated by Django 2.1.5 on 2019-02-25 07:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20190225_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subtitle',
            field=ckeditor.fields.RichTextField(verbose_name='Subtitle'),
        ),
    ]
