# Generated by Django 2.1.5 on 2019-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Key Name')),
                ('name', models.CharField(max_length=200, verbose_name='Social Network')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['name'],
            },
        ),
    ]
